ishare-satellite:
  fullnameOverride: "satellite"

  config:
    id: "EU.EORI.NL000000000"
    key: |
      test
    crt: |
      test

    trusted_list:
      - name: iSHARETestCA
        status: "granted"
        validity: "valid"
        crt: |
          -----BEGIN CERTIFICATE-----
          <iSHARETestCA Certificate>
          -----END CERTIFICATE-----

      - name: FIWARETEST-CA
        status: "granted"
        validity: "valid"
        crt: |
          -----BEGIN CERTIFICATE-----
          <FIWARETEST-CA Certificate>
          -----END CERTIFICATE-----

    parties:
      - id: "EU.EORI.NLPACKETDEL"
        name: "Packet Delivery Company"
        status: "Active"
        start_date: "2021-09-27T00:00:00Z"
        end_date: "2051-09-27T00:00:00Z"
        crt: |
          -----BEGIN CERTIFICATE-----
          <Packet Delivery Company Certificate>
          -----END CERTIFICATE-----
        capability_url: "https://idp.packetdel.com/capabilities" # Optional
        certifications: # Optional
          - role: "IdentityProvider"
            start_date: "2021-09-27T00:00:00Z"
            end_date: "2051-09-27T00:00:00Z"
            loa: 3