apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-configmap
data:
  kong.yml: |
    _format_version: "2.1"
    _transform: true
    services:
      - host: "release-name-apollo"
        name: "apollo"
        port: 8080
        protocol: http
        routes:
          - name: apollo
            paths: 
              - /apollo
            strip_path: true
        plugins:
          - name: ngsi-ishare-policies
            config:
              access_token:
                header_names:
                  - "authorization"
                  - "Authorization"
              ar:
                identifier: "EU.EORI.NL000000004"
                host: "https://ar.isharetest.net"
                token_endpoint: "https://ar.isharetest.net/connect/token"
                delegation_endpoint: "https://ar.isharetest.net/delegation"
              satellite:
                identifier: "EU.EORI.FIWARESATELLITE"
                host: "http://satellite.infra.svc.cluster.local:8080"
                token_endpoint: "http://satellite.infra.svc.cluster.local:8080/token"
                trusted_list_endpoint: "http://satellite.infra.svc.cluster.local:8080/trusted_list"
              jws:
                identifier: "EU.EORI.SMARTSHEPHERD"
    
          - name: request-transformer
            config:
              remove:
                headers:
                  - Authorization
                  - authorization
    
      - host: "release-name-orion-ld"
        name: "orion-ld-passthrough"
        port: 1026
        protocol: http
        routes:
          - name: orion-ld-passthrough
            paths:
              - /passthrough
    
      - host: "release-name-orion-ld"
        name: "orion-ld"
        port: 1026
        protocol: http
        routes:
          - name: orion-ld
            paths:
              - /orion
            strip_path: true
        plugins:
          - name: ngsi-ishare-policies
            config:
              access_token:
                header_names:
                  - "authorization"
                  - "Authorization"
              ar:
                identifier: "EU.EORI.NL000000004"
                host: "https://ar.isharetest.net"
                token_endpoint: "https://ar.isharetest.net/connect/token"
                delegation_endpoint: "https://ar.isharetest.net/delegation"
              satellite:
                identifier: "EU.EORI.FIWARESATELLITE"
                host: "http://satellite.infra.svc.cluster.local:8080"
                token_endpoint: "http://satellite.infra.svc.cluster.local:8080/token"
                trusted_list_endpoint: "http://satellite.infra.svc.cluster.local:8080/trusted_list"
              jws:
                identifier: "EU.EORI.SMARTSHEPHERD"
              
          - name: request-transformer
            config:
              remove:
                headers:
                  - Authorization
                  - authorization