name: Integration-test

on:
  push

jobs:
  it:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v1
      with:
        java-version: '17'
        java-package: jdk

    - name: Run test
      id: test
      run: |
        mvn clean integration-test
        